### ISSUE TITLE
precompiled NIF is not available: Compilation fails on M2

### ISSUE THREAD

**Issue by connorsmallman** [martinthenth/uuidv7#26]
First of all thanks for the project. Unfortunately I'm having an issue running my app within an Alpine image on an M2 Mac 

== Compilation error in file lib/uuidv7.ex ==
** (RuntimeError) precompiled NIF is not available for this target: "aarch64-unknown-linux-musl".
The available targets are:
- aarch64-unknown-linux-gnu
- aarch64-apple-darwin
- riscv64gc-unknown-linux-gnu
- x86_64-apple-darwin
- x86_64-unknown-linux-gnu
- x86_64-unknown-linux-musl
lib/uuidv7.ex:90: (module)
could not compile dependency :uuidv7, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile uuidv7 --force", update it with "mix deps.update uuidv7" or clean it with "mix deps.clean uuidv7"

**Comment by sebasortiz-dev** [comment]
Same error on M1 Macbook

**Comment by martinthenth** [comment]
Hi! Thanks for the report. It looks like the `rustler_precompiled` app needs an update and the images a rebuild. The mentioned image is available in the defaults: https://hexdocs.pm/rustler_precompiled/RustlerPrecompiled.html

**Comment by martinthenth** [comment]
👋🏻 I upgraded the library and built new NIFs with additional build targets, including `aarch64-unknown-linux-musl`. Can you check it works for you?

**Comment by martinthenth** [comment]
The new builds should work as expected so I'm closing this issue. Let me know if there is any problem
