### ISSUE TITLE
** (RuntimeError) precompiled NIF is not available for this target: "armv7l-unknown-linux-gnueabihf"

### ISSUE THREAD

**Issue by paulo-silva** [martinthenth/uuidv7#38]
I am getting this error while trying to install uuidv7 in Raspberry PI 3

**Comment by martinthenth** [comment]
Hi! Thanks for the report. The issue is that `armv7l-unknown-linux-gnueabihf` isn't enabled by default in the `rustler_precompiled` library, so the solution would be to add it to the list of target builds

**Comment by martinthenth** [comment]
Hi! This issue is fixed by https://github.com/martinthenth/uuidv7/pull/62, and I'm going to release this change as `v1.0.0` probably this week.
